### ISSUE TITLE
has a compiler warning C4067: unexpected tokens following preprocessor directive - expected a newline

### ISSUE THREAD

**Issue by hihihlo** [biojppm/c4core#5]
when use Visual Studio 2015 (on windows 10),
it appear a warning as below :
c4/charconv.hpp(13): warning C4067: unexpected tokens following preprocessor directive - expected a newline

is it possible to avoid the warning ?

**Comment by biojppm** [comment]
sure. Is this the only place where you see the warning? Can you paste the output from a full compilation?

**Comment by biojppm** [comment]
I did a [brief investigation](https://godbolt.org/z/eoT8Dg), and this is because VS2015 cannot handle the feature test macros. I can rework that test until it gets no errors in VS2015, but FYI I've been thinking of dropping support for VS2015, and require at least VS2017.

Can you update your VS to 2019 or 2017? It should be a clean compilation then.

**Comment by biojppm** [comment]
Actually VS2017 19.10 also issues a warning on that line. So let me find a way to address this.

**Comment by hihihlo** [comment]
if VS2019 won't the warning, then i will drop VS2015 too.
thank you for your help ~
